### ISSUE TITLE
Restoring from backup made from mihon

### ISSUE THREAD

**Issue by heeeeeeeeeeh** [Suwayomi/Suwayomi-JUI#90]
Explain What the feature is and how it should work in detail. Remove this line after you are done.
I would like to be able to restore backups made from mihon. I don't want to spend hours adding manga and marking the chapters I read

**Comment by Syer10** [comment]
You can already

**Comment by pavonismc** [comment]
help it is asking for a gz file. but my backup is a tachibk file

**Comment by heeeeeeeeeeh** [comment]
Change the Extension of the file from tachibk to .proto.gz

**Comment by pavonismc** [comment]
ok, i will. thanks
